Switch windows image to use aqtinstall

diff --git a/Dockerfile.windows b/Dockerfile.windows
--- a/Dockerfile.windows
+++ b/Dockerfile.windows
@@ -1,26 +1,20 @@
-FROM archlinux:latest
+FROM --platform=linux/amd64 debian:buster
 
-RUN echo "VerbosePkgLists" >> /etc/pacman.conf
-RUN echo "ParallelDownloads = 5" >> /etc/pacman.conf
-RUN pacman --noconfirm -Syyu
+RUN apt-get update
 
-# Add mingw-repo
-RUN \
-        pacman-key --init \
-    &&  pacman-key --recv-keys B9E36A7275FC61B464B67907E06FE8F53CDC6A4C \
-    &&  pacman-key --finger    B9E36A7275FC61B464B67907E06FE8F53CDC6A4C \
-    &&  pacman-key --lsign-key B9E36A7275FC61B464B67907E06FE8F53CDC6A4C \
-    &&  echo "[ownstuff]" >> /etc/pacman.conf \
-    &&  echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf \
-    &&  echo "Server = https://ftp.f3l.de/~martchus/\$repo/os/\$arch" >> /etc/pacman.conf \
-    &&  echo "Server = https://martchus.no-ip.biz/repo/arch/\$repo/os/\$arch" >> /etc/pacman.conf \
-    &&  pacman -Sy
+RUN apt-get install -y python3-pip
 
-# Install MinGW toolchain
-RUN pacman --noconfirm -S \
-    make \
-    mingw-w64-cmake \
-    mingw-w64-qt5-base
+RUN pip3 install aqtinstall
+
+RUN aqt install-tool windows desktop tools_cmake qt.tools.cmake.win64 --outputdir /opt/qt
+
+RUN aqt install-tool windows desktop tools_mingw qt.tools.win64_mingw810 --outputdir /opt/qt
+
+RUN aqt install-qt windows desktop 5.15.2 win64_mingw81 --outputdir /opt/qt --archives qtbase \
+    || echo
+# (Ugly workaround because aqt fails trying to launch qmake.exe)
+
+RUN apt-get install -y cmake mingw-w64
 
 ENV OUTPUT_DIR /workdir/output
 WORKDIR /workdir
